apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bek4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0022-tenant/ci10t-777-0022-app/devfile-sample-bek4@sha256:4fe60a0c951270be53af0ef51161c64f87bc2af277c137deff56dc32ce71c683
        name: my-nodejs
        resources: {}
status: {}
